# Generated by Django 3.2.12 on 2022-04-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platos', '0002_alter_plato_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
